//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Broadway.Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUserRole
    {
        public System.Guid UserId { get; set; }
        public System.Guid RoleId { get; set; }
        public Nullable<System.Guid> UserId1 { get; set; }
        public Nullable<System.Guid> RoleId1 { get; set; }
    
        public virtual AspNetRole AspNetRole { get; set; }
        public virtual AspNetRole AspNetRole1 { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
    }
}
