//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Broadway.Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class DropDownType
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public System.Guid OrgId { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public int DropdownTypes { get; set; }
        public string Alias { get; set; }
    }
}
